import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import { resolveSocialGeneration, localSocialTemplate } from '../utils/hardening/socialGenerationTruth';

// Regression guard for item 13. POST /api/social/generate substituted a fixed
// marketing template when the AI provider was unconfigured or errored, then
// answered `success: true` with no field distinguishing model output from the
// canned fallback. Callers (the YouTube modal already read `data.draft`) could
// present the template as generated copy. server.ts binds a port on import, so
// the route assertions read the source text, matching socialDraftAuditTruth.test.ts.
const serverSource = fs.readFileSync(path.resolve(process.cwd(), 'server.ts'), 'utf8');
const serverFlat = serverSource.replace(/\s+/g, ' ');
const modalFlat = fs
  .readFileSync(path.resolve(process.cwd(), 'src/components/SocialMediaModal.tsx'), 'utf8')
  .replace(/\s+/g, ' ');

describe('resolveSocialGeneration credits model output only when the provider wrote it', () => {
  it('credits non-empty model output to the AI provider', () => {
    const truth = resolveSocialGeneration({ generatedContent: 'Real model copy about launches.', topic: 'Launch' });
    expect(truth.source).toBe('ai');
    expect(truth.aiGenerated).toBe(true);
    expect(truth.content).toBe('Real model copy about launches.');
    expect(truth.notice).toMatch(/generated by the AI provider/i);
  });

  it('falls back to a disclosed local template when the provider returned nothing', () => {
    for (const empty of ['', '   ', '\n\t']) {
      const truth = resolveSocialGeneration({ generatedContent: empty, topic: 'Launch' });
      expect(truth.source).toBe('local_template');
      expect(truth.aiGenerated).toBe(false);
      expect(truth.content).toContain('Launch');
      expect(truth.content).toMatch(/\[Local template — not AI-generated\]/);
      expect(truth.notice).toMatch(/not AI-generated/i);
    }
  });

  it('the template names the topic and labels itself a template', () => {
    const text = localSocialTemplate('Quantum Computing');
    expect(text).toContain('Quantum Computing');
    expect(text).toContain('[Local template — not AI-generated]');
  });
});

describe('POST /api/social/generate discloses the draft origin instead of implying AI', () => {
  const route = serverFlat.slice(
    serverFlat.indexOf("app.post('/api/social/generate'"),
    serverFlat.indexOf("app.post('/api/social/action'"),
  );

  it('routes the draft through the truth helper', () => {
    expect(route).toContain('resolveSocialGeneration(');
  });

  it('records the generation source, aiGenerated flag, and notice on the post', () => {
    expect(route).toContain('generationSource: generation.source');
    expect(route).toContain('aiGenerated: generation.aiGenerated');
    expect(route).toContain('generationNotice: generation.notice');
  });

  it('no longer stores the raw provider text as the post content', () => {
    expect(route).not.toContain('content: generatedContent');
  });

  it('keeps the fallback template in exactly one place (the helper)', () => {
    // The route previously embedded the template inline, so it could not disclose it.
    expect(route).not.toContain('saves 10+ hours per week');
  });
});

describe('the social UI cannot present a local template as AI-generated', () => {
  it('the YouTube generator reads the post the route actually returns', () => {
    // `data.draft` never existed, so the AI title/description/hashtags were dropped.
    expect(modalFlat).toContain('const draft = data.post ?? data.draft;');
    expect(modalFlat).not.toContain('if (data.success && data.draft) {');
  });

  it('discloses a local template and claims AI generation only for real output', () => {
    expect(modalFlat).toContain("draft.generationSource === 'local_template'");
    expect(modalFlat).toContain('It is not AI-generated.');
  });

  it('renders a disclosure banner when the draft is a local template', () => {
    expect(modalFlat).toContain("selectedPost.generationSource === 'local_template'");
  });
});
