// ==============================================================================
// HERMES JARVIS — SOCIAL GENERATION TRUTH
//
// POST /api/social/generate drafts a social post from a topic. When the AI
// provider was unconfigured or errored, the route substituted a fixed marketing
// template ("Perspective on ... saves 10+ hours per week") and still answered
// `success: true`, with no field distinguishing model output from the canned
// fallback. Any caller could present the template as generated copy — the
// YouTube modal already read `data.draft` and announced "AI-generated".
//
// The route must disclose which content the provider wrote and which is a local
// fallback, so no surface can claim an AI post the provider never produced.
// ==============================================================================

export type SocialGenerationSource = 'ai' | 'local_template';

export interface SocialGenerationInput {
  /** Trimmed model output, or empty when the provider produced nothing. */
  generatedContent: string;
  topic: string;
}

export interface SocialGenerationTruth {
  /** The content to draft: model output when present, otherwise the local template. */
  content: string;
  /** 'ai' only when the provider returned non-empty text; 'local_template' otherwise. */
  source: SocialGenerationSource;
  /** True only for model-generated content. */
  aiGenerated: boolean;
  /** Human-readable disclosure of the content's real origin. */
  notice: string;
}

const cleanTopic = (topic: string | undefined): string =>
  typeof topic === 'string' && topic.trim() ? topic.trim() : 'Autonomous AI Workflows';

/**
 * The fixed local fallback post, used only when no model output exists. The
 * text names itself a template so it is never mistaken for generated copy.
 */
export function localSocialTemplate(topic: string | undefined): string {
  return `💡 Perspective on ${cleanTopic(topic)}:\n\n1. Building with autonomous tools saves 10+ hours per week.\n2. Zero-cost infrastructure allows rapid prototyping.\n3. Human-in-the-loop verification guarantees precision.\n\nWhat are you automating next?\n\n#ArtificialIntelligence #Engineering #DevOps #Innovation #BuildInPublic\n\n[Local template — not AI-generated]`;
}

/**
 * Resolves the draft content and its true origin. Non-empty model output is
 * credited to the model; anything else is an explicit local template carrying a
 * disclosure notice, so `success: true` never implies the provider wrote it.
 */
export function resolveSocialGeneration(input: SocialGenerationInput): SocialGenerationTruth {
  const aiText = typeof input.generatedContent === 'string' ? input.generatedContent.trim() : '';
  if (aiText) {
    return {
      content: aiText,
      source: 'ai',
      aiGenerated: true,
      notice: 'Content generated by the AI provider.',
    };
  }
  return {
    content: localSocialTemplate(input.topic),
    source: 'local_template',
    aiGenerated: false,
    notice:
      'No AI provider produced content for this draft; a fixed local template was used. This is not AI-generated text.',
  };
}
